language: go

go:
  - 1.1
  - tip

install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go build github.com/axw/gocov/gocov
  - go build github.com/mattn/goveralls

script: ../../../../bin/goveralls 2aDqkKyVGr9Tl20GgyOACi607G6ZbpSMV
